"""Tcl placement script writer.

Emits a sourceable script that snaps macros to their placed locations inside
Synopsys IC Compiler II or Cadence Innovus. Both dialects are supported;
coordinates are lower-left corner microns, matching what both tools expect.
"""

from pathlib import Path
from typing import Dict, Tuple


def write_tcl(
    placements: Dict[str, Tuple[float, float]],
    design,
    out_path,
    dialect: str = "icc2",
    fix_macros: bool = True,
):
    """Write placement commands for every component in `placements`.

    dialect: "icc2" (set_cell_location / set_fixed_objects) or
             "innovus" (placeInstance).
    fix_macros: also mark the placed macros fixed so later placement steps
                do not move them (the usual flow after macro placement).
    """
    if dialect not in ("icc2", "innovus"):
        raise ValueError(f"unknown tcl dialect: {dialect}")
    lines = [
        f"# Macro placement for design '{design.name}'",
        "# Generated by eda_io (varrahan v2 macro placer)",
        "# Coordinates: lower-left corner, microns",
        "",
    ]
    for name in sorted(placements):
        x, y = placements[name]
        comp = design.components.get(name)
        orient = comp.orient if comp else "N"
        if dialect == "icc2":
            lines.append(
                f"set_cell_location -coordinates {{{x:.4f} {y:.4f}}}"
                f" -orientation {orient} [get_cells {{{name}}}]"
            )
        else:
            lines.append(
                f"placeInstance {name} {x:.4f} {y:.4f} {orient}"
                + (" -fixed" if fix_macros else "")
            )
    if dialect == "icc2" and fix_macros:
        names = " ".join(sorted(placements))
        lines += ["", f"set_fixed_objects [get_cells {{{names}}}]"]
    lines.append("")
    Path(out_path).write_text("\n".join(lines))
